import { IGameCardContent } from "@/types/home-page";

export const gameSlides: IGameCardContent[] = [
  {
    id: "1",
    posterImg: "/images/posters/poster-6.jpg",
    gameName: "Introductiong check6 extraction dlc",
    date: "12 Feb 2024",
    site: "Visit Site",
  },
  {
    id: "2",
    posterImg: "/images/posters/poster-7.webp",
    gameName: "Introductiong check6 extraction dlc",
    date: "18 March 2024",
    site: "Visit Site",
  },
  {
    id: "3",
    posterImg: "/images/posters/poster-8.webp",
    gameName: "Introductiong check6 extraction dlc",
    date: "19 Apr 2024",
    site: "Visit Site",
  },
  {
    id: "4",
    posterImg: "/images/posters/poster-9.jpg",
    gameName: "Introductiong check6 extraction dlc",
    date: "11 Feb 2025",
    site: "Visit Site",
  },
  {
    id: "5",
    posterImg: "/images/posters/poster-10.jpg",
    gameName: "Introductiong check6 extraction dlc",
    date: "10 Sep 2026",
    site: "Visit Site",
  },
  {
    id: "6",
    posterImg: "/images/posters/poster-11.png",
    gameName: "Introductiong check6 extraction dlc",
    date: "21 Aug 2021",
    site: "Visit Site",
  },
  {
    id: "7",
    posterImg: "/images/posters/poster-12.jpg",
    gameName: "Introductiong check6 extraction dlc",
    date: "15 Dec 2024",
    site: "Visit Site",
  },
];
export const nextCardGameSlides: IGameCardContent[] = [
  {
    id: "1",
    posterImg: "/images/posters/poster-7.webp",
    gameName: "Introductiong check6 extraction dlc",
    date: "12 Feb 2024",
    site: "Visit Site",
  },
  {
    id: "2",
    posterImg: "/images/posters/poster-6.jpg",
    gameName: "Introductiong check6 extraction dlc",
    date: "18 March 2024",
    site: "Visit Site",
  },
  {
    id: "3",
    posterImg: "/images/posters/poster-8.webp",
    gameName: "Introductiong check6 extraction dlc",
    date: "19 Apr 2024",
    site: "Visit Site",
  },
  {
    id: "4",
    posterImg: "/images/posters/poster-9.jpg",
    gameName: "Introductiong check6 extraction dlc",
    date: "11 Feb 2025",
    site: "Visit Site",
  },
  {
    id: "5",
    posterImg: "/images/posters/poster-10.jpg",
    gameName: "Introductiong check6 extraction dlc",
    date: "10 Sep 2026",
    site: "Visit Site",
  },
  {
    id: "6",
    posterImg: "/images/posters/poster-11.png",
    gameName: "Introductiong check6 extraction dlc",
    date: "21 Aug 2021",
    site: "Visit Site",
  },
  {
    id: "7",
    posterImg: "/images/posters/poster-12.jpg",
    gameName: "Introductiong check6 extraction dlc",
    date: "15 Dec 2024",
    site: "Visit Site",
  },
];
export const newsSlides: IGameCardContent[] = [
  {
    id: "1",
    posterImg: "/images/posters/poster-15.png",
    gameName: "Introductiong check6 extraction dlc",
    date: "12 Feb 2024",
    site: "Visit Site",
  },
  {
    id: "2",
    posterImg: "/images/posters/poster-13.webp",
    gameName: "Introductiong check6 extraction dlc",
    date: "18 March 2024",
    site: "Visit Site",
  },
  {
    id: "3",
    posterImg: "/images/posters/poster-14.jpg",
    gameName: "Introductiong check6 extraction dlc",
    date: "19 Apr 2024",
    site: "Visit Site",
  },
  {
    id: "4",
    posterImg: "/images/posters/poster-16.jpg",
    gameName: "Introductiong check6 extraction dlc",
    date: "11 Feb 2025",
    site: "Visit Site",
  },
  {
    id: "5",
    posterImg: "/images/posters/poster-10.jpg",
    gameName: "Introductiong check6 extraction dlc",
    date: "10 Sep 2026",
    site: "Visit Site",
  },
  {
    id: "6",
    posterImg: "/images/posters/poster-11.png",
    gameName: "Introductiong check6 extraction dlc",
    date: "21 Aug 2021",
    site: "Visit Site",
  },
  {
    id: "7",
    posterImg: "/images/posters/poster-12.jpg",
    gameName: "Introductiong check6 extraction dlc",
    date: "15 Dec 2024",
    site: "Visit Site",
  },
];
